{
 "title": "Job",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "filters" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(requests_started_total, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Job requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of job calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(requests_started_total{job=~\"$job_name\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "endpoint_requests_started_total{job=~\"$job_name\"}",
     "legendFormat": "{{job}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Internal Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(request_internal_errors_total{job=~\"$job_name\"}[$__rate_interval])) by (job, endpoint)",
     "legendFormat": "{{job}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Job active requests (Unfinished)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "requests_started_total{job=~\"$job_name\"} - requests_done_total{job=~\"$job_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Job response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Response time histogram over time",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(idelta(request_duration_bucket{job=~\"$job_name\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response time histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(request_duration_bucket{job=~\"$job_name\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Job Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(request_duration_sum{job=~\"$job_name\"}) by (job) / sum(request_duration_count{job=~\"$job_name\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg(up{job=~\"$job_name\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - avg(process_start_time_seconds{job=~\"$job_name\"}) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"$job_name\"})",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "sum(rate(python_gc_collections_total{job=~\"$job_name\"}[$__rate_interval]))",
     "legendFormat": "GC collections rate"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Virtual memory (approximate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=~\"$job_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU usage (approximate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job_name\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory usage (seen by k8s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"ikp-rt\", container!=\"\", pod=~\"${job_name}.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}