{
 "title": "image-builder",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "image builder (API server) CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"image-builder\"}[5m])"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"image-builder\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"image-builder\"})",
     "legendFormat": "seconds uptime"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"image-builder\"}"
    }
   ]
  },
  { "title": "Building Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Image building requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "images_built_total{job=\"image-builder\"}",
     "legendFormat": "total built images"
    },
    {
     "expr": "sum(image_building_requests_total{job=\"image-builder\"})",
     "legendFormat": "total building requests"
    },
    {
     "expr": "image_building_requests_total{job=\"image-builder\"}",
     "legendFormat": "requests of {{job_name}} {{job_version}}"
    },
    {
     "expr": "sum(increase(image_building_requests_total{job=\"image-builder\"}[1m]))",
     "legendFormat": "requests growth"
    }
   ]
  },
  {
   "title": "Building errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "images_buidling_errors_total{job=\"image-builder\"}",
     "legendFormat": "total errors"
    }
   ]
  },
  {
   "title": "Average overall building time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "image_building_request_duration_seconds_total{job=\"image-builder\"} / image_building_done_requests_total{job=\"image-builder\"}",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "Pushing to registry time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "images_pushed_duration_total{job=\"image-builder\"} / images_pushed_total{job=\"image-builder\"}",
     "legendFormat": "{{job_name}} {{job_version}}"
    }
   ]
  },
  {
   "title": "building vs pushing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(images_pushed_duration_total{job=\"image-builder\"}) / sum(images_pushed_total{job=\"image-builder\"})",
     "legendFormat": "average pushing to registry time"
    },
    {
     "expr": "sum(image_building_request_duration_seconds_total{job=\"image-builder\"}) / sum(image_building_done_requests_total{job=\"image-builder\"}) - sum(images_pushed_duration_total{job=\"image-builder\"}) / sum(images_pushed_total{job=\"image-builder\"})",
     "legendFormat": "average building time"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "active_building_tasks{job=\"image-builder\"}",
     "legendFormat": "active image-building tasks"
    }
   ]
  }
 ]
}