global:
  scrape_interval: 5s
  evaluation_interval: 1m

scrape_configs:
  - job_name: postgres-exporter
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "postgres-exporter:9187"

  - job_name: lifecycle
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "lifecycle:7102"

  - job_name: image-builder
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "image-builder:7101"

  - job_name: pub
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "pub:7105"

  - job_name: job-v-0-0-1
    scheme: http
    metrics_path: /metrics
    dns_sd_configs:
      - names: 
          - 'job-adder-v-0-0-1'
        type: A
        port: 7000
