---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ fatman_k8s_namespace }}
  name: {{ resource_name }}
  labels:
    app: {{ fatman_k8s_namespace }}
    app.kubernetes.io/name: {{ resource_name }}
    racetrack/fatman: {{ resource_name }}
    racetrack/fatman-name: {{ manifest.name }}
    racetrack/fatman-version: {{ manifest.version }}
spec:
  replicas: {{ manifest.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ resource_name }}
  template:
    metadata:
      labels:
        app: {{ fatman_k8s_namespace }}
        app.kubernetes.io/name: {{ resource_name }}
        racetrack/fatman: {{ resource_name }}
        racetrack/resource: fatman
        racetrack/fatman-name: {{ manifest.name }}
        racetrack/fatman-version: {{ manifest.version }}
      annotations:
        racetrack-deployment-date: "{{ deployment_timestamp }}"
    spec:
      securityContext:
        supplementalGroups: [200000]
        fsGroup: 200000
        runAsUser: 100000
        runAsGroup: 100000
      imagePullSecrets:
        - name: docker-registry-read-secret
      containers:
        - name: {{ resource_name }}
          image: "{{ entrypoint_image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
          resources:
            requests:
              memory: "{{ memory_min }}"
              cpu: "{{ cpu_min }}"
            limits:
              memory: "{{ memory_max }}"
              cpu: "{{ cpu_max }}"
          env:
{% for env_key, env_value in env_vars.items() %}
            - name: {{ env_key }}
              value: "{{ env_value }}"
{% endfor %}
{% if user_module_image %}
        - name: {{ user_module_container }}
          image: "{{ user_module_image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 7004
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
          resources:
            requests:
              memory: "{{ memory_min }}"
              cpu: "{{ cpu_min }}"
            limits:
              memory: "{{ memory_max }}"
              cpu: "{{ cpu_max }}"
{% if env_vars %}
          env:
{% for env_key, env_value in env_vars.items() %}
            - name: {{ env_key }}
              value: "{{ env_value }}"
{% endfor %}
{% endif %}

{% endif %}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ fatman_k8s_namespace }}
  name: {{ resource_name }}
  labels:
    app: {{ fatman_k8s_namespace }}
    app.kubernetes.io/name: {{ resource_name }}
    racetrack/fatman: {{ resource_name }}
    racetrack/fatman-name: {{ manifest.name }}
    racetrack/fatman-version: {{ manifest.version }}
spec:
  selector:
    app.kubernetes.io/name: {{ resource_name }}
  type: ClusterIP
  ports:
    - name: http
      port: 7000
      targetPort: 7000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ fatman_k8s_namespace }}
  name: {{ resource_name }}
  labels:
    app: {{ resource_name }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ resource_name }}
  endpoints:
  - port: http
