---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ fatman_k8s_namespace }}
  name: {{ resource_name }}
  labels:
    app: {{ fatman_k8s_namespace }}
    racetrack/fatman: {{ resource_name }}
    racetrack/fatman-name: {{ fatman_name }}
    racetrack/fatman-version: {{ fatman_version }}
data:
  git_credentials: "{{ git_credentials }}"
  secret_build_env: "{{ secret_build_env }}"
  secret_runtime_env: "{{ secret_runtime_env }}"
